# Generated by Django 3.2.4 on 2021-06-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_regra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regra',
        ),
    ]
