# Generated by Django 3.2.4 on 2021-06-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_delete_regra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
